package com.example.demo.entities;
// Generated Mar 18, 2018 9:17:03 PM by Hibernate Tools 4.3.1

import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Commit generated by hbm2java
 */
@Entity
@Table(name = "commit")
public class Commit {

    private int commitId;
    private String message;
    private Programmer programmer;

    public Commit() {
    }

    public Commit(int commitId) {
        this.commitId = commitId;
    }

    @Id
    @Column(name = "commit_id", unique = true, nullable = false)
    public int getCommitId() {
        return this.commitId;
    }

    public void setCommitId(int commitId) {
        this.commitId = commitId;
    }

    @Column(name = "message")
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @ManyToOne
    public Programmer getProgrammer() {
        return this.programmer;
    }

    public void setProgrammer(Set programmerHasCommits) {
        this.programmer = programmer;
    }

}


