package com.example.demo.entities;
// Generated Mar 18, 2018 9:17:03 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person",
         schema = "test"
)
public class Person implements java.io.Serializable {

    private int personId;
    private String name;
    private String surname;
    private Date dateOfBirth;
    private Programmer programmer;

    public Person() {
    }

    public Person(int personId) {
        this.personId = personId;
    }

    public Person(int personId, String name, String surname, Date dateOfBirth, Programmer programmer) {//, Set programmerHasCommits, Set programmerHasTasks) {
        this.personId = personId;
        this.name = name;
        this.surname = surname;
        this.dateOfBirth = dateOfBirth;
        this.programmer = programmer;
//       this.programmerHasCommits = programmerHasCommits;
//       this.programmerHasTasks = programmerHasTasks;
    }

    @Id
    @GeneratedValue(generator = "generator")
    @Column(name = "person_id", unique = true, nullable = false)
    public int getPersonId() {
        return this.personId;
    }

    public void setPersonId(int personId) {
        this.personId = personId;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "surname")
    public String getSurname() {
        return this.surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_of_birth", length = 13)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    @OneToOne(fetch = FetchType.LAZY, mappedBy = "person")
    public Programmer getProgrammer() {
        return this.programmer;
    }

    public void setProgrammer(Programmer programmer) {
        this.programmer = programmer;
    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
//    public Set getProgrammerHasCommits() {
//        return this.programmerHasCommits;
//    }
//    
//    public void setProgrammerHasCommits(Set programmerHasCommits) {
//        this.programmerHasCommits = programmerHasCommits;
//    }
//
//@OneToMany(fetch=FetchType.LAZY, mappedBy="person")
//    public Set getProgrammerHasTasks() {
//        return this.programmerHasTasks;
//    }
//    
//    public void setProgrammerHasTasks(Set programmerHasTasks) {
//        this.programmerHasTasks = programmerHasTasks;
//    }

}
