package com.example.demo.entities;
// Generated Mar 18, 2018 9:17:03 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task",
         schema = "test"
)
public class Task implements java.io.Serializable { //annotations?

    private int taskId;
    private String message;
    private Programmer programmer;

    public Task() {
    }

    public Task(int taskId) {
        this.taskId = taskId;
    }

    public Task(int taskId, String message, Programmer programmer) {
        this.taskId = taskId;
        this.message = message;
        this.programmer = programmer;
    }

    @Id

    @Column(name = "task_id", unique = true, nullable = false)
    public int getTaskId() {
        return this.taskId;
    }

    public void setTaskId(int taskId) {
        this.taskId = taskId;
    }

    @Column(name = "message")
    public String getMessage() {
        return this.message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "task")
    public Programmer getProgrammer() {
        return this.programmer;
    }

    public void setProgrammer(Programmer programmer) {
        this.programmer = programmer;
    }

}
